export const useDeck1 = [
  {
    id: 1,
    img: "battleCard/first_deck/1.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 10,
    attack: 6,
  },
  {
    id: 2,
    img: "battleCard/first_deck/2.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 6,
    attack: 6,
  },
  {
    id: 3,
    img: "battleCard/first_deck/3.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 1,
    attack: 6,
  },
  {
    id: 4,
    img: "battleCard/first_deck/4.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 5,
    attack: 7,
  },
  {
    id: 5,
    img: "battleCard/first_deck/5.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 1,
    attack: 5,
  },
  {
    id: 6,
    img: "battleCard/first_deck/6.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 6,
    attack: 8,
  },
  {
    id: 7,
    img: "battleCard/first_deck/7.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 4,
    attack: 8,
  },
  {
    id: 8,
    img: "battleCard/first_deck/8.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 5,
    attack: 8,
  },
  {
    id: 9,
    img: "battleCard/first_deck/9.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 3,
    attack: 10,
  },
  {
    id: 10,
    img: "battleCard/first_deck/10.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 4,
    attack: 9,
  },
  {
    id: 11,
    img: "battleCard/first_deck/11.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 6,
    attack: 7,
  },
  {
    id: 12,
    img: "battleCard/first_deck/12.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 5,
    attack: 7,
  },
  {
    id: 13,
    img: "battleCard/first_deck/13.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 4,
    attack: 7,
  },
  {
    id: 14,
    img: "battleCard/first_deck/14.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 12,
    attack: 6,
  },
  {
    id: 15,
    img: "battleCard/first_deck/15.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 6,
    attack: 6,
  },
  {
    id: 16,
    img: "battleCard/first_deck/16.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 4,
    attack: 7,
  },
  {
    id: 17,
    img: "battleCard/first_deck/17.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 10,
    attack: 6,
  },
  {
    id: 18,
    img: "battleCard/first_deck/18.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 5,
    attack: 7,
  },
  {
    id: 19,
    img: "battleCard/first_deck/19.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 4,
    attack: 8,
  },
  {
    id: 20,
    img: "battleCard/first_deck/20.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 5,
    attack: 8,
  },
  {
    id: 21,
    img: "battleCard/first_deck/21.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 5,
    attack: 8,
  },
  {
    id: 22,
    img: "battleCard/first_deck/22.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 4,
    attack: 5,
  },
  {
    id: 23,
    img: "battleCard/first_deck/23.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 4,
    attack: 4,
  },
  {
    id: 24,
    img: "battleCard/first_deck/24.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 4,
    attack: 4,
  },
  {
    id: 25,
    img: "battleCard/first_deck/25.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 5,
    attack: 9,
  },
  {
    id: 26,
    img: "battleCard/first_deck/26.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 4,
    attack: 6,
  },
  {
    id: 27,
    img: "battleCard/first_deck/27.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 4,
    attack: 5,
  },
  {
    id: 28,
    img: "battleCard/first_deck/28.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 4,
    attack: 4,
  },
];

export const useDeck2 = [
  {
    id: 29,
    img: "battleCard/first_deck/1.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 10,
    attack: 6,
  },
  {
    id: 30,
    img: "battleCard/first_deck/2.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 6,
    attack: 6,
  },
  {
    id: 31,
    img: "battleCard/first_deck/3.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 1,
    attack: 6,
  },
  {
    id: 32,
    img: "battleCard/first_deck/4.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 5,
    attack: 7,
  },
  {
    id: 33,
    img: "battleCard/first_deck/5.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 1,
    attack: 5,
  },
  {
    id: 34,
    img: "battleCard/first_deck/6.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 6,
    attack: 8,
  },
  {
    id: 35,
    img: "battleCard/first_deck/7.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 4,
    attack: 8,
  },
  {
    id: 36,
    img: "battleCard/first_deck/8.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 5,
    attack: 8,
  },
  {
    id: 38,
    img: "battleCard/first_deck/9.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 3,
    attack: 10,
  },
  {
    id: 39,
    img: "battleCard/first_deck/10.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 4,
    attack: 9,
  },
  {
    id: 40,
    img: "battleCard/first_deck/11.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 6,
    attack: 7,
  },
  {
    id: 41,
    img: "battleCard/first_deck/12.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 5,
    attack: 7,
  },
  {
    id: 42,
    img: "battleCard/first_deck/13.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 4,
    attack: 7,
  },
  {
    id: 43,
    img: "battleCard/first_deck/14.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 12,
    attack: 6,
  },
  {
    id: 44,
    img: "battleCard/first_deck/15.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 6,
    attack: 6,
  },
  {
    id: 45,
    img: "battleCard/first_deck/16.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 4,
    attack: 7,
  },
  {
    id: 46,
    img: "battleCard/first_deck/17.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 10,
    attack: 6,
  },
  {
    id: 47,
    img: "battleCard/first_deck/18.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 5,
    attack: 7,
  },
  {
    id: 48,
    img: "battleCard/first_deck/19.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 4,
    attack: 8,
  },
  {
    id: 49,
    img: "battleCard/first_deck/20.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 5,
    attack: 8,
  },
  {
    id: 50,
    img: "battleCard/first_deck/21.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 5,
    attack: 8,
  },
  {
    id: 51,
    img: "battleCard/first_deck/22.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 4,
    attack: 5,
  },
  {
    id: 52,
    img: "battleCard/first_deck/23.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 4,
    attack: 4,
  },
  {
    id: 53,
    img: "battleCard/first_deck/24.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 4,
    attack: 4,
  },
  {
    id: 54,
    img: "battleCard/first_deck/25.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 5,
    attack: 9,
  },
  {
    id: 55,
    img: "battleCard/first_deck/26.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 4,
    attack: 6,
  },
  {
    id: 56,
    img: "battleCard/first_deck/27.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 4,
    attack: 5,
  },
  {
    id: 57,
    img: "battleCard/first_deck/28.png",
    name: "Geralt of Rivia",
    faction: "Witcher",
    info: `If that's what it takes to save the world, it's better to let that world die.`,
    power: 4,
    attack: 4,
  },
];