export const useDeck1 = [
    { id: "1", img: "battleCard/first_deck/1.png", power: 10 ,attack:6},
    { id: "2", img: "battleCard/first_deck/2.png", power: 6 ,attack:6},
    { id: "3", img: "battleCard/first_deck/3.png", power: 1 ,attack:6},
    { id: "4", img: "battleCard/first_deck/4.png", power: 5 ,attack:7},
    { id: "5", img: "battleCard/first_deck/5.png", power: 1,attack:5 },
    { id: "6", img: "battleCard/first_deck/6.png", power: 6 ,attack:8},
    { id: "7", img: "battleCard/first_deck/7.png", power: 4 ,attack:8},
    { id: "8", img: "battleCard/first_deck/8.png", power: 5 ,attack:8},
    { id: "9", img: "battleCard/first_deck/9.png", power: 3,attack:10 },
    { id: "10", img: "battleCard/first_deck/10.png", power: 4 ,attack:9},
    { id: "11", img: "battleCard/first_deck/11.png", power: 6 ,attack:7},
    { id: "12", img: "battleCard/first_deck/12.png", power: 5 ,attack:7},
    { id: "13", img: "battleCard/first_deck/13.png", power: 4 ,attack:7},
    { id: "14", img: "battleCard/first_deck/14.png", power: 12 ,attack:6},
    { id: "15", img: "battleCard/first_deck/15.png", power: 6,attack:6 },
    { id: "16", img: "battleCard/first_deck/16.png", power: 4,attack:7 },
    { id: "17", img: "battleCard/first_deck/17.png", power: 10 ,attack:6},
    { id: "18", img: "battleCard/first_deck/18.png", power: 5,attack:7 },
    { id: "19", img: "battleCard/first_deck/19.png", power: 4,attack:8 },
    { id: "20", img: "battleCard/first_deck/20.png", power: 5 ,attack:8},
    { id: "21", img: "battleCard/first_deck/21.png", power: 5 ,attack:8},
    { id: "22", img: "battleCard/first_deck/22.png", power: 4,attack:5 },
    { id: "23", img: "battleCard/first_deck/23.png", power: 4 ,attack:4},
    { id: "24", img: "battleCard/first_deck/24.png", power: 4,attack:4 },
    { id: "25", img: "battleCard/first_deck/25.png", power: 5 ,attack:9},
    { id: "26", img: "battleCard/first_deck/26.png", power: 4,attack:6 },
    { id: "27", img: "battleCard/first_deck/27.png", power: 4,attack:5 },
    { id: "28", img: "battleCard/first_deck/28.png", power: 4 ,attack:4},
   
  ];

  export const useDeck2 = [
    { id: "1", img: "battleCard/first_deck/1.png", power: 10 ,attack:6},
    { id: "2", img: "battleCard/first_deck/2.png", power: 6 ,attack:6},
    { id: "3", img: "battleCard/first_deck/3.png", power: 1 ,attack:6},
    { id: "4", img: "battleCard/first_deck/4.png", power: 5 ,attack:7},
    { id: "5", img: "battleCard/first_deck/5.png", power: 1,attack:5 },
    { id: "6", img: "battleCard/first_deck/6.png", power: 6 ,attack:8},
    { id: "7", img: "battleCard/first_deck/7.png", power: 4 ,attack:8},
    { id: "8", img: "battleCard/first_deck/8.png", power: 5 ,attack:8},
    { id: "9", img: "battleCard/first_deck/9.png", power: 3,attack:10 },
    { id: "10", img: "battleCard/first_deck/10.png", power: 4 ,attack:9},
    { id: "11", img: "battleCard/first_deck/11.png", power: 6 ,attack:7},
    { id: "12", img: "battleCard/first_deck/12.png", power: 5 ,attack:7},
    { id: "13", img: "battleCard/first_deck/13.png", power: 4 ,attack:7},
    { id: "14", img: "battleCard/first_deck/14.png", power: 12 ,attack:6},
    { id: "15", img: "battleCard/first_deck/15.png", power: 6,attack:6 },
    { id: "16", img: "battleCard/first_deck/16.png", power: 4,attack:7 },
    { id: "17", img: "battleCard/first_deck/17.png", power: 10 ,attack:6},
    { id: "18", img: "battleCard/first_deck/18.png", power: 5,attack:7 },
    { id: "19", img: "battleCard/first_deck/19.png", power: 4,attack:8 },
    { id: "20", img: "battleCard/first_deck/20.png", power: 5 ,attack:8},
    { id: "21", img: "battleCard/first_deck/21.png", power: 5 ,attack:8},
    { id: "22", img: "battleCard/first_deck/22.png", power: 4,attack:5 },
    { id: "23", img: "battleCard/first_deck/23.png", power: 4 ,attack:4},
    { id: "24", img: "battleCard/first_deck/24.png", power: 4,attack:4 },
    { id: "25", img: "battleCard/first_deck/25.png", power: 5 ,attack:9},
    { id: "26", img: "battleCard/first_deck/26.png", power: 4,attack:6 },
    { id: "27", img: "battleCard/first_deck/27.png", power: 4,attack:5 },
    { id: "28", img: "battleCard/first_deck/28.png", power: 4 ,attack:4},
  ];